package com.spring.app.demovaadinapplication.vaadin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DesignerViewDesign extends VerticalLayout {

    protected Label messageFromService;

    public DesignerViewDesign(){
        Design.read(this);
    }
}
